//          Copyright Odin Holmes 2016.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE.md or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
#pragma once

#include "algorithm/all.hpp"
#include "algorithm/any.hpp"
#include "algorithm/count_if.hpp"
#include "algorithm/filter.hpp"
#include "algorithm/find_if.hpp"
#include "algorithm/flatten.hpp"
#include "algorithm/fold_left.hpp"
#include "algorithm/fold_right.hpp"
#include "algorithm/partition.hpp"
#include "algorithm/remove_adjacent.hpp"
#include "algorithm/remove_if.hpp"
#include "algorithm/reverse.hpp"
#include "algorithm/sort.hpp"
#include "algorithm/transform.hpp"
#include "algorithm/zip_with.hpp"
#include "algorithm/make_sequence.hpp"

#include "functional/bind.hpp"
#include "functional/call.hpp"
#include "functional/compose.hpp"
#include "functional/fork.hpp"
#include "functional/identity.hpp"

#include "functions/arithmetic/complement.hpp"
#include "functions/arithmetic/decrement.hpp"
#include "functions/arithmetic/divide.hpp"
#include "functions/arithmetic/increment.hpp"
#include "functions/arithmetic/max.hpp"
#include "functions/arithmetic/min.hpp"
#include "functions/arithmetic/minus.hpp"
#include "functions/arithmetic/modulo.hpp"
#include "functions/arithmetic/negate.hpp"
#include "functions/arithmetic/plus.hpp"
#include "functions/arithmetic/times.hpp"
#include "functions/bitwise/bitwise_and.hpp"
#include "functions/bitwise/bitwise_not.hpp"
#include "functions/bitwise/bitwise_or.hpp"
#include "functions/bitwise/bitwise_xor.hpp"

#include "sequence/at.hpp"
#include "sequence/create.hpp"
#include "sequence/is_list.hpp"
#include "sequence/join.hpp"
#include "sequence/pop_front.hpp"
#include "sequence/push_back.hpp"
#include "sequence/push_front.hpp"
#include "sequence/size.hpp"
#include "sequence/front.hpp"

#include "types/bool.hpp"
#include "types/int.hpp"
#include "types/integral_constant.hpp"
#include "types/list.hpp"
#include "types/nothing.hpp"

#include "utility/always.hpp"
#include "utility/identity.hpp"
#include "utility/invert.hpp"
#include "utility/is_instance.hpp"
